/*

 INTRO1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\julia\Documents\U of T\Year3\MIE438\tiles\menu_whiteonblack.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Intro1MapWidth 20
#define Intro1MapHeight 18
#define Intro1MapBank 0

extern unsigned char Intro1Map[];

/* End of INTRO1.H */
