/*

 LVL1BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 23 x 20
   Tile set      : lvl1_maptiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BlankBackgroundMapWidth 23
#define BlankBackgroundMapHeight 20
#define BlankBackgroundMapBank 0

#define BlankBackgroundMap BlankBackgroundMapPLN0
extern unsigned char BlankBackgroundMapPLN0[];
extern unsigned char BlankBackgroundMapPLN1[];

/* End of LVL1BACKGROUNDMAP.H */
