/*

 BOSSBACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 23 x 20
   Tile set      : C:\Users\Claire Glossop\Documents\MIE438_GB\MIE438_Git\MIE438-GameBoy-Project\Backgrounds\lvl1_maptiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BossBackgroundMapWidth 23
#define BossBackgroundMapHeight 20
#define BossBackgroundMapBank 0

#define BossBackgroundMap BossBackgroundMapPLN0
extern unsigned char BossBackgroundMapPLN0[];
extern unsigned char BossBackgroundMapPLN1[];

/* End of BOSSBACKGROUNDMAP.H */
