/*

 GAMESPRITE_FROG.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define GameSprite_FrogBank 0

/* Super Gameboy palette 0 */
#define GameSprite_FrogSGBPal0c0 6076
#define GameSprite_FrogSGBPal0c1 8935
#define GameSprite_FrogSGBPal0c2 6596
#define GameSprite_FrogSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define GameSprite_FrogSGBPal1c0 6076
#define GameSprite_FrogSGBPal1c1 8935
#define GameSprite_FrogSGBPal1c2 6596
#define GameSprite_FrogSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define GameSprite_FrogSGBPal2c0 6076
#define GameSprite_FrogSGBPal2c1 8935
#define GameSprite_FrogSGBPal2c2 6596
#define GameSprite_FrogSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define GameSprite_FrogSGBPal3c0 6076
#define GameSprite_FrogSGBPal3c1 8935
#define GameSprite_FrogSGBPal3c2 6596
#define GameSprite_FrogSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define GameSprite_FrogCGBPal0c0 32767
#define GameSprite_FrogCGBPal0c1 6125
#define GameSprite_FrogCGBPal0c2 1539
#define GameSprite_FrogCGBPal0c3 1252

/* Gameboy Color palette 1 */
#define GameSprite_FrogCGBPal1c0 32767
#define GameSprite_FrogCGBPal1c1 1539
#define GameSprite_FrogCGBPal1c2 1252
#define GameSprite_FrogCGBPal1c3 0

/* Gameboy Color palette 2 */
#define GameSprite_FrogCGBPal2c0 6076
#define GameSprite_FrogCGBPal2c1 8935
#define GameSprite_FrogCGBPal2c2 6596
#define GameSprite_FrogCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define GameSprite_FrogCGBPal3c0 6076
#define GameSprite_FrogCGBPal3c1 8935
#define GameSprite_FrogCGBPal3c2 6596
#define GameSprite_FrogCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define GameSprite_FrogCGBPal4c0 6076
#define GameSprite_FrogCGBPal4c1 8935
#define GameSprite_FrogCGBPal4c2 6596
#define GameSprite_FrogCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define GameSprite_FrogCGBPal5c0 6076
#define GameSprite_FrogCGBPal5c1 8935
#define GameSprite_FrogCGBPal5c2 6596
#define GameSprite_FrogCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define GameSprite_FrogCGBPal6c0 6076
#define GameSprite_FrogCGBPal6c1 8935
#define GameSprite_FrogCGBPal6c2 6596
#define GameSprite_FrogCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define GameSprite_FrogCGBPal7c0 6076
#define GameSprite_FrogCGBPal7c1 8935
#define GameSprite_FrogCGBPal7c2 6596
#define GameSprite_FrogCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char GameSprite_FrogCGB[];
/* Start of tile array. */
extern unsigned char GameSprite_Frog[];

/* End of GAMESPRITE_FROG.H */
