/*

 LVL1BACKGROUNDMAP_ALT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 23 x 20
   Tile set      : C:\Users\Claire Glossop\Documents\MIE438_GB\MIE438_Git\MIE438-GameBoy-Project\Backgrounds\lvl1_maptiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Lvl1BackgroundMap_altWidth 23
#define Lvl1BackgroundMap_altHeight 20
#define Lvl1BackgroundMap_altBank 0

#define Lvl1BackgroundMap_alt Lvl1BackgroundMap_altPLN0
extern unsigned char Lvl1BackgroundMap_altPLN0[];
extern unsigned char Lvl1BackgroundMap_altPLN1[];

/* End of LVL1BACKGROUNDMAP_ALT.H */
