/*

 LVL1BACKGROUNDDATA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Lvl1BackgroundDataBank 0

/* Super Gameboy palette 0 */
#define Lvl1BackgroundDataSGBPal0c0 6076
#define Lvl1BackgroundDataSGBPal0c1 8935
#define Lvl1BackgroundDataSGBPal0c2 6596
#define Lvl1BackgroundDataSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Lvl1BackgroundDataSGBPal1c0 6076
#define Lvl1BackgroundDataSGBPal1c1 8935
#define Lvl1BackgroundDataSGBPal1c2 6596
#define Lvl1BackgroundDataSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Lvl1BackgroundDataSGBPal2c0 6076
#define Lvl1BackgroundDataSGBPal2c1 8935
#define Lvl1BackgroundDataSGBPal2c2 6596
#define Lvl1BackgroundDataSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Lvl1BackgroundDataSGBPal3c0 6076
#define Lvl1BackgroundDataSGBPal3c1 8935
#define Lvl1BackgroundDataSGBPal3c2 6596
#define Lvl1BackgroundDataSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Lvl1BackgroundDataCGBPal0c0 6076
#define Lvl1BackgroundDataCGBPal0c1 8935
#define Lvl1BackgroundDataCGBPal0c2 6596
#define Lvl1BackgroundDataCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define Lvl1BackgroundDataCGBPal1c0 32767
#define Lvl1BackgroundDataCGBPal1c1 21140
#define Lvl1BackgroundDataCGBPal1c2 10570
#define Lvl1BackgroundDataCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Lvl1BackgroundDataCGBPal2c0 11055
#define Lvl1BackgroundDataCGBPal2c1 1192
#define Lvl1BackgroundDataCGBPal2c2 5605
#define Lvl1BackgroundDataCGBPal2c3 480

/* Gameboy Color palette 3 */
#define Lvl1BackgroundDataCGBPal3c0 11055
#define Lvl1BackgroundDataCGBPal3c1 8943
#define Lvl1BackgroundDataCGBPal3c2 11050
#define Lvl1BackgroundDataCGBPal3c3 10991

/* Gameboy Color palette 4 */
#define Lvl1BackgroundDataCGBPal4c0 28539
#define Lvl1BackgroundDataCGBPal4c1 21140
#define Lvl1BackgroundDataCGBPal4c2 15855
#define Lvl1BackgroundDataCGBPal4c3 10570

/* Gameboy Color palette 5 */
#define Lvl1BackgroundDataCGBPal5c0 21140
#define Lvl1BackgroundDataCGBPal5c1 32023
#define Lvl1BackgroundDataCGBPal5c2 22545
#define Lvl1BackgroundDataCGBPal5c3 14373

/* Gameboy Color palette 6 */
#define Lvl1BackgroundDataCGBPal6c0 6076
#define Lvl1BackgroundDataCGBPal6c1 8935
#define Lvl1BackgroundDataCGBPal6c2 6596
#define Lvl1BackgroundDataCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define Lvl1BackgroundDataCGBPal7c0 6076
#define Lvl1BackgroundDataCGBPal7c1 8935
#define Lvl1BackgroundDataCGBPal7c2 6596
#define Lvl1BackgroundDataCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char Lvl1BackgroundDataCGB[];
/* Start of tile array. */
extern unsigned char Lvl1BackgroundData[];

/* End of LVL1BACKGROUNDDATA.H */
