/*

 LVL1BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 23 x 20
   Tile set      : lvl1_maptiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Lvl1BackgroundMapWidth 23
#define Lvl1BackgroundMapHeight 20
#define Lvl1BackgroundMapBank 0

#define Lvl1BackgroundMap Lvl1BackgroundMapPLN0
extern unsigned char Lvl1BackgroundMapPLN0[];
extern unsigned char Lvl1BackgroundMapPLN1[];

/* End of LVL1BACKGROUNDMAP.H */
