/*

 MAINBACKGROUNDDATA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define MainBackgroundDataBank 0

/* Super Gameboy palette 0 */
#define MainBackgroundDataSGBPal0c0 6076
#define MainBackgroundDataSGBPal0c1 8935
#define MainBackgroundDataSGBPal0c2 6596
#define MainBackgroundDataSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define MainBackgroundDataSGBPal1c0 6076
#define MainBackgroundDataSGBPal1c1 8935
#define MainBackgroundDataSGBPal1c2 6596
#define MainBackgroundDataSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define MainBackgroundDataSGBPal2c0 6076
#define MainBackgroundDataSGBPal2c1 8935
#define MainBackgroundDataSGBPal2c2 6596
#define MainBackgroundDataSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define MainBackgroundDataSGBPal3c0 6076
#define MainBackgroundDataSGBPal3c1 8935
#define MainBackgroundDataSGBPal3c2 6596
#define MainBackgroundDataSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define MainBackgroundDataCGBPal0c0 2452
#define MainBackgroundDataCGBPal0c1 1395
#define MainBackgroundDataCGBPal0c2 1329
#define MainBackgroundDataCGBPal0c3 0

/* Gameboy Color palette 1 */
#define MainBackgroundDataCGBPal1c0 32767
#define MainBackgroundDataCGBPal1c1 21140
#define MainBackgroundDataCGBPal1c2 10570
#define MainBackgroundDataCGBPal1c3 0

/* Gameboy Color palette 2 */
#define MainBackgroundDataCGBPal2c0 2452
#define MainBackgroundDataCGBPal2c1 1329
#define MainBackgroundDataCGBPal2c2 1441
#define MainBackgroundDataCGBPal2c3 1345

/* Gameboy Color palette 3 */
#define MainBackgroundDataCGBPal3c0 11055
#define MainBackgroundDataCGBPal3c1 8943
#define MainBackgroundDataCGBPal3c2 11050
#define MainBackgroundDataCGBPal3c3 10991

/* Gameboy Color palette 4 */
#define MainBackgroundDataCGBPal4c0 28539
#define MainBackgroundDataCGBPal4c1 21140
#define MainBackgroundDataCGBPal4c2 15855
#define MainBackgroundDataCGBPal4c3 10570

/* Gameboy Color palette 5 */
#define MainBackgroundDataCGBPal5c0 21140
#define MainBackgroundDataCGBPal5c1 32023
#define MainBackgroundDataCGBPal5c2 22545
#define MainBackgroundDataCGBPal5c3 14373

/* Gameboy Color palette 6 */
#define MainBackgroundDataCGBPal6c0 72
#define MainBackgroundDataCGBPal6c1 8226
#define MainBackgroundDataCGBPal6c2 1345
#define MainBackgroundDataCGBPal6c3 1196

/* Gameboy Color palette 7 */
#define MainBackgroundDataCGBPal7c0 21140
#define MainBackgroundDataCGBPal7c1 2688
#define MainBackgroundDataCGBPal7c2 127
#define MainBackgroundDataCGBPal7c3 28672
/* CGBpalette entries. */
extern unsigned char MainBackgroundDataCGB[];
/* Start of tile array. */
extern unsigned char MainBackgroundData[];

/* End of MAINBACKGROUNDDATA.H */
