/*

 SIGNALBACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 23 x 20
   Tile set      : main_maptiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define SignalBackgroundMapWidth 23
#define SignalBackgroundMapHeight 20
#define SignalBackgroundMapBank 0

#define SignalBackgroundMap SignalBackgroundMapPLN0
extern unsigned char SignalBackgroundMapPLN0[];
extern unsigned char SignalBackgroundMapPLN1[];

/* End of SIGNALBACKGROUNDMAP.H */
