/*

 ENDSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\julia\Documents\U of T\Year3\gbtd22\letters.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define endMapWidth 20
#define endMapHeight 18
#define endMapBank 0

extern unsigned char endMap[];

/* End of ENDSCREEN.H */
