/*

 MAZE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\conno\Documents\U of T\3rd Year\MIE438\Tile Designer\maze_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mazeWidth 20
#define mazeHeight 18
#define mazeBank 0

extern unsigned char maze[];

/* End of MAZE.H */
