/*

 MENU.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 10
   Tile set      : C:\Users\julia\Documents\U of T\Year3\gbtd22\menu.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MenuWidth 8
#define MenuHeight 10
#define MenuBank 0

extern unsigned char Menu[];

/* End of MENU.H */
