/*

 SIMPLE_BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\conno\Documents\U of T\3rd Year\MIE438\Tile Designer\simple_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundmapWidth 40
#define backgroundmapHeight 18
#define backgroundmapBank 0

extern unsigned char backgroundmap[];

/* End of SIMPLE_BACKGROUND.H */
