/*

 DIAG2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 5
   Tile set      : C:\Users\julia\Documents\U of T\Year3\MIE438\tiles\menu_whiteonblack.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Diag2Width 20
#define Diag2Height 5
#define Diag2Bank 0

extern unsigned char Diag2[];

/* End of DIAG2.H */
