/*

 DIAG1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 5
   Tile set      : C:\Users\julia\Documents\U of T\Year3\MIE438\tiles\menu_whiteonblack.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Diag1Width 20
#define Diag1Height 5
#define Diag1Bank 0

extern unsigned char Diag1[];

/* End of DIAG1.H */
