/*

 LVL1TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 73

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Lvl1TilesBank 0

/* Super Gameboy palette 0 */
#define Lvl1TilesSGBPal0c0 6076
#define Lvl1TilesSGBPal0c1 8935
#define Lvl1TilesSGBPal0c2 6596
#define Lvl1TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Lvl1TilesSGBPal1c0 6076
#define Lvl1TilesSGBPal1c1 8935
#define Lvl1TilesSGBPal1c2 6596
#define Lvl1TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Lvl1TilesSGBPal2c0 6076
#define Lvl1TilesSGBPal2c1 8935
#define Lvl1TilesSGBPal2c2 6596
#define Lvl1TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Lvl1TilesSGBPal3c0 6076
#define Lvl1TilesSGBPal3c1 8935
#define Lvl1TilesSGBPal3c2 6596
#define Lvl1TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Lvl1TilesCGBPal0c0 6076
#define Lvl1TilesCGBPal0c1 8935
#define Lvl1TilesCGBPal0c2 6596
#define Lvl1TilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define Lvl1TilesCGBPal1c0 32767
#define Lvl1TilesCGBPal1c1 21140
#define Lvl1TilesCGBPal1c2 10570
#define Lvl1TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Lvl1TilesCGBPal2c0 11055
#define Lvl1TilesCGBPal2c1 1192
#define Lvl1TilesCGBPal2c2 5605
#define Lvl1TilesCGBPal2c3 480

/* Gameboy Color palette 3 */
#define Lvl1TilesCGBPal3c0 11055
#define Lvl1TilesCGBPal3c1 8943
#define Lvl1TilesCGBPal3c2 11050
#define Lvl1TilesCGBPal3c3 10991

/* Gameboy Color palette 4 */
#define Lvl1TilesCGBPal4c0 28539
#define Lvl1TilesCGBPal4c1 21140
#define Lvl1TilesCGBPal4c2 15855
#define Lvl1TilesCGBPal4c3 10570

/* Gameboy Color palette 5 */
#define Lvl1TilesCGBPal5c0 21140
#define Lvl1TilesCGBPal5c1 10570
#define Lvl1TilesCGBPal5c2 0
#define Lvl1TilesCGBPal5c3 3199

/* Gameboy Color palette 6 */
#define Lvl1TilesCGBPal6c0 6076
#define Lvl1TilesCGBPal6c1 8935
#define Lvl1TilesCGBPal6c2 6596
#define Lvl1TilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define Lvl1TilesCGBPal7c0 6076
#define Lvl1TilesCGBPal7c1 8935
#define Lvl1TilesCGBPal7c2 6596
#define Lvl1TilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char Lvl1TilesCGB[];
/* Start of tile array. */
extern unsigned char Lvl1Tiles[];

/* End of LVL1TILES.H */
