/*

 LVL1BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 39 x 20
   Tile set      : C:\Users\Claire Glossop\Downloads\gbtd22\lvl1_maptiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Lvl1BackgroundMapWidth 39
#define Lvl1BackgroundMapHeight 20
#define Lvl1BackgroundMapBank 0

extern unsigned char Lvl1BackgroundMap[];

/* End of LVL1BACKGROUNDMAP.H */
