/*

 LVL1ALLDATA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Lvl1AllDataBank 0

/* Super Gameboy palette 0 */
#define Lvl1AllDataSGBPal0c0 6076
#define Lvl1AllDataSGBPal0c1 8935
#define Lvl1AllDataSGBPal0c2 6596
#define Lvl1AllDataSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Lvl1AllDataSGBPal1c0 6076
#define Lvl1AllDataSGBPal1c1 8935
#define Lvl1AllDataSGBPal1c2 6596
#define Lvl1AllDataSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Lvl1AllDataSGBPal2c0 6076
#define Lvl1AllDataSGBPal2c1 8935
#define Lvl1AllDataSGBPal2c2 6596
#define Lvl1AllDataSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Lvl1AllDataSGBPal3c0 6076
#define Lvl1AllDataSGBPal3c1 8935
#define Lvl1AllDataSGBPal3c2 6596
#define Lvl1AllDataSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Lvl1AllDataCGBPal0c0 6076
#define Lvl1AllDataCGBPal0c1 8935
#define Lvl1AllDataCGBPal0c2 6596
#define Lvl1AllDataCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define Lvl1AllDataCGBPal1c0 32767
#define Lvl1AllDataCGBPal1c1 21140
#define Lvl1AllDataCGBPal1c2 10570
#define Lvl1AllDataCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Lvl1AllDataCGBPal2c0 11055
#define Lvl1AllDataCGBPal2c1 1192
#define Lvl1AllDataCGBPal2c2 5605
#define Lvl1AllDataCGBPal2c3 480

/* Gameboy Color palette 3 */
#define Lvl1AllDataCGBPal3c0 11055
#define Lvl1AllDataCGBPal3c1 8943
#define Lvl1AllDataCGBPal3c2 11050
#define Lvl1AllDataCGBPal3c3 10991

/* Gameboy Color palette 4 */
#define Lvl1AllDataCGBPal4c0 28539
#define Lvl1AllDataCGBPal4c1 21140
#define Lvl1AllDataCGBPal4c2 15855
#define Lvl1AllDataCGBPal4c3 10570

/* Gameboy Color palette 5 */
#define Lvl1AllDataCGBPal5c0 21140
#define Lvl1AllDataCGBPal5c1 10570
#define Lvl1AllDataCGBPal5c2 159
#define Lvl1AllDataCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Lvl1AllDataCGBPal6c0 6076
#define Lvl1AllDataCGBPal6c1 8935
#define Lvl1AllDataCGBPal6c2 6596
#define Lvl1AllDataCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define Lvl1AllDataCGBPal7c0 6076
#define Lvl1AllDataCGBPal7c1 8935
#define Lvl1AllDataCGBPal7c2 6596
#define Lvl1AllDataCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char Lvl1AllDataCGB[];
/* Start of tile array. */
extern unsigned char Lvl1AllData[];

/* End of LVL1ALLDATA.H */
