/*

 MENUMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 9
   Tile set      : C:\Users\julia\Documents\U of T\Year3\MIE438\MIE438-GameBoy-Project\Test_Background\lvl1_mapmenutiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MenuDataWidth 8
#define MenuDataHeight 9
#define MenuDataBank 0

#define MenuData MenuDataPLN0
extern unsigned char MenuDataPLN0[];
extern unsigned char MenuDataPLN1[];

/* End of MENUMAP.H */
