/*

 MENUMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 9
   Tile set      : lvl1_maptiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MenuMapWidth 8
#define MenuMapHeight 9
#define MenuMapBank 0

#define MenuMap MenuMapPLN0
extern unsigned char MenuMapPLN0[];
extern unsigned char MenuMapPLN1[];

/* End of MENUMAP.H */
