/*

 BKGCIRCLESMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 25 x 32
   Tile set      : circlestileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkgcirclesmapWidth 25
#define bkgcirclesmapHeight 32
#define bkgcirclesmapBank 0

extern unsigned char bkgcirclesmap[];

/* End of BKGCIRCLESMAP.H */
