/*

 HEATSPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char HeatSprites[] =
{
  0x08,0x00,0x38,0x00,0x21,0x00,0x50,0x42,
  0x56,0x22,0x4A,0x02,0x42,0x06,0x02,0x20,
  0x02,0x40,0x74,0x00,0x14,0x08,0x52,0x08,
  0x12,0x00,0x32,0x01,0x23,0x40,0x86,0x00
};

/* End of HEATSPRITES.C */
