/*

 ARROW_SPIRTE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char ArrowSprite[] =
{
  0x00,0x00,0x20,0x20,0x30,0x30,0x38,0x38,
  0x30,0x30,0x20,0x20,0x00,0x00,0x00,0x00
};

/* End of ARROW_SPIRTE.C */
