/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 20
   Tile set      : C:\Users\Claire Glossop\Downloads\gbtd22\tileset_general.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMapWidth 40
#define BackgroundMapHeight 20
#define BackgroundMapBank 0

#define BackgroundMap BackgroundMapPLN0
extern unsigned char BackgroundMapPLN0[];
extern unsigned char BackgroundMapPLN1[];

/* End of BACKGROUNDMAP.H */
