/*

 GAMESPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 90

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define GameSpritesBank 0

/* Super Gameboy palette 0 */
#define GameSpritesSGBPal0c0 6076
#define GameSpritesSGBPal0c1 8935
#define GameSpritesSGBPal0c2 6596
#define GameSpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define GameSpritesSGBPal1c0 6076
#define GameSpritesSGBPal1c1 8935
#define GameSpritesSGBPal1c2 6596
#define GameSpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define GameSpritesSGBPal2c0 6076
#define GameSpritesSGBPal2c1 8935
#define GameSpritesSGBPal2c2 6596
#define GameSpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define GameSpritesSGBPal3c0 6076
#define GameSpritesSGBPal3c1 8935
#define GameSpritesSGBPal3c2 6596
#define GameSpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define GameSpritesCGBPal0c0 32767
#define GameSpritesCGBPal0c1 991
#define GameSpritesCGBPal0c2 28
#define GameSpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define GameSpritesCGBPal1c0 32767
#define GameSpritesCGBPal1c1 15855
#define GameSpritesCGBPal1c2 26425
#define GameSpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define GameSpritesCGBPal2c0 32767
#define GameSpritesCGBPal2c1 545
#define GameSpritesCGBPal2c2 28539
#define GameSpritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define GameSpritesCGBPal3c0 32767
#define GameSpritesCGBPal3c1 32189
#define GameSpritesCGBPal3c2 23567
#define GameSpritesCGBPal3c3 14377

/* Gameboy Color palette 4 */
#define GameSpritesCGBPal4c0 32767
#define GameSpritesCGBPal4c1 15855
#define GameSpritesCGBPal4c2 31
#define GameSpritesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define GameSpritesCGBPal5c0 32767
#define GameSpritesCGBPal5c1 991
#define GameSpritesCGBPal5c2 543
#define GameSpritesCGBPal5c3 29

/* Gameboy Color palette 6 */
#define GameSpritesCGBPal6c0 32767
#define GameSpritesCGBPal6c1 545
#define GameSpritesCGBPal6c2 1351
#define GameSpritesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define GameSpritesCGBPal7c0 32767
#define GameSpritesCGBPal7c1 31
#define GameSpritesCGBPal7c2 15
#define GameSpritesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char GameSpritesCGB[];
/* Start of tile array. */
extern unsigned char GameSprites[];

/* End of GAMESPRITES.H */
