/*

 MEMBACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 23 x 20
   Tile set      : lvl1_maptiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MemBackgroundMapWidth 23
#define MemBackgroundMapHeight 20
#define MemBackgroundMapBank 0

#define MemBackgroundMap MemBackgroundMapPLN0
extern unsigned char MemBackgroundMapPLN0[];
extern unsigned char MemBackgroundMapPLN1[];

/* End of MEMBACKGROUNDMAP.H */
