/*

 NEWBACKGROUNDDATA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define NewBackgroundDataBank 0

/* Super Gameboy palette 0 */
#define NewBackgroundDataSGBPal0c0 6076
#define NewBackgroundDataSGBPal0c1 8935
#define NewBackgroundDataSGBPal0c2 6596
#define NewBackgroundDataSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define NewBackgroundDataSGBPal1c0 6076
#define NewBackgroundDataSGBPal1c1 8935
#define NewBackgroundDataSGBPal1c2 6596
#define NewBackgroundDataSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define NewBackgroundDataSGBPal2c0 6076
#define NewBackgroundDataSGBPal2c1 8935
#define NewBackgroundDataSGBPal2c2 6596
#define NewBackgroundDataSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define NewBackgroundDataSGBPal3c0 6076
#define NewBackgroundDataSGBPal3c1 8935
#define NewBackgroundDataSGBPal3c2 6596
#define NewBackgroundDataSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define NewBackgroundDataCGBPal0c0 2452
#define NewBackgroundDataCGBPal0c1 1395
#define NewBackgroundDataCGBPal0c2 1329
#define NewBackgroundDataCGBPal0c3 0

/* Gameboy Color palette 1 */
#define NewBackgroundDataCGBPal1c0 32767
#define NewBackgroundDataCGBPal1c1 21140
#define NewBackgroundDataCGBPal1c2 10570
#define NewBackgroundDataCGBPal1c3 0

/* Gameboy Color palette 2 */
#define NewBackgroundDataCGBPal2c0 11055
#define NewBackgroundDataCGBPal2c1 1355
#define NewBackgroundDataCGBPal2c2 5605
#define NewBackgroundDataCGBPal2c3 480

/* Gameboy Color palette 3 */
#define NewBackgroundDataCGBPal3c0 11055
#define NewBackgroundDataCGBPal3c1 8943
#define NewBackgroundDataCGBPal3c2 11050
#define NewBackgroundDataCGBPal3c3 10991

/* Gameboy Color palette 4 */
#define NewBackgroundDataCGBPal4c0 28539
#define NewBackgroundDataCGBPal4c1 21140
#define NewBackgroundDataCGBPal4c2 15855
#define NewBackgroundDataCGBPal4c3 10570

/* Gameboy Color palette 5 */
#define NewBackgroundDataCGBPal5c0 21140
#define NewBackgroundDataCGBPal5c1 32023
#define NewBackgroundDataCGBPal5c2 22545
#define NewBackgroundDataCGBPal5c3 14373

/* Gameboy Color palette 6 */
#define NewBackgroundDataCGBPal6c0 72
#define NewBackgroundDataCGBPal6c1 8226
#define NewBackgroundDataCGBPal6c2 1345
#define NewBackgroundDataCGBPal6c3 1196

/* Gameboy Color palette 7 */
#define NewBackgroundDataCGBPal7c0 6076
#define NewBackgroundDataCGBPal7c1 8935
#define NewBackgroundDataCGBPal7c2 6596
#define NewBackgroundDataCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char NewBackgroundDataCGB[];
/* Start of tile array. */
extern unsigned char NewBackgroundData[];

/* End of NEWBACKGROUNDDATA.H */
