/*

 MENU.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 7
   Tile set      : C:\Users\julia\Documents\U of T\Year3\MIE438\tiles\menu_blackonwhite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MenuMapWidth 8
#define MenuMapHeight 7
#define MenuMapBank 0

extern unsigned char MenuMap[];

/* End of MENU.H */
